default: &default
  adapter: postgresql
  encoding: unicode
  username: ukirama
  password: '123'
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: clean_blog_development

test:
  <<: *default
  database: clean_blog_test

production:
  <<: *default
  database: clean_blog_production
  username: ukirama
  password: <%= ENV['CLEAN_BLOG_DATABASE_PASSWORD'] %>
